### ISSUE TITLE
Is there an easy way to compile multiple files?

### ISSUE THREAD

**Issue by lemonlambda** [jorbDehmel/oak#5]
Is there any easy way to compile multiple files or do I have to write a build script manually?

**Comment by jorbDehmel** [comment]
As it is right now, the compiler can take multiple input files (either from the command line or from `include!` statements), but can only target one output file (whether it be `c`, object code, or an executable). This is because, under the hood, it collates all `Oak` definitions into a single output `c` file, then compiles and/or links that.

Thus, a build script is probably what you want.

**Comment by lemonlambda** [comment]
Weird then, I have this project structure
```
.
├── build.sh
├── flake.lock
├── flake.nix
├── oak_package_info.txt
└── src
   ├── linked_list.oak
   └── main.oak
```
and when I run this command:
![20231231_22h01m43s_grim](https://github.com/jorbDehmel/oak/assets/55360995/a67646c4-35ea-496a-bcf0-5cbb1a9a64f1)
it creates that error.

src of `main.oak`:
```rs
package!("std");
use_rule!("std");

include!("linked_list.oak");

let main() -> i32
{
    0
}
```

**Comment by jorbDehmel** [comment]
Looks like it's attempting to include package files over local ones. Just pushed a fix

**Comment by lemonlambda** [comment]
That fixes it thanks.
